In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
arr1=np.arange(20,41)
arr1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [8]:
arr2=np.ones(10)*5
arr2

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [12]:
arr3=np.random.randint(1,50,24)
arr3

array([48,  2,  5, 14, 16, 26, 17, 13, 41,  3, 17, 35, 19, 25, 14,  4, 32,
       47, 19,  5,  7,  6, 27, 42])

In [13]:
arr3.reshape(3,4,2)

array([[[48,  2],
        [ 5, 14],
        [16, 26],
        [17, 13]],

       [[41,  3],
        [17, 35],
        [19, 25],
        [14,  4]],

       [[32, 47],
        [19,  5],
        [ 7,  6],
        [27, 42]]])

In [15]:
arr4=np.random.rand(4,5)
arr4

array([[0.13553186, 0.67521501, 0.13599748, 0.99470683, 0.11805324],
       [0.2481497 , 0.68032335, 0.36456329, 0.55972022, 0.47073663],
       [0.57054428, 0.78950325, 0.48929756, 0.505976  , 0.90075291],
       [0.83073507, 0.42424422, 0.92287737, 0.26649202, 0.23282161]])

In [16]:
np.random.seed(123)
arr5=np.random.randint(1,50,20)
arr5[arr5%2==0]=-1
arr5

array([-1,  3, 29, 35, 39, -1, -1, 43, 23, -1, 33, -1, -1, 33, 47, 33, -1,
       -1, -1, 15])