# Numpy ->
> Python Library designed for scientific computation

> Multi-dimensional array

> Fast and Efficient that ordinary python lists

1-d array - vector

2-d array - matrix

n-d array - tensor


In [1]:
import numpy as np

In [3]:
nums1=[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
nums2=[[1,2,3],[4,5,6]]
nums1=np.array(nums1)
nums1


array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [4]:
nums2=np.array(nums2)
nums2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
#  function return the number of dimensions of an array
nums1.ndim

3

In [6]:
nums2.ndim

2

In [7]:
nums1.shape

(2, 2, 3)

In [8]:
nums1.dtype

dtype('int32')

### Create Numpy arrays using Functions

zeros

ones

eye

diag

randint

rand

randn

In [9]:
arr1=np.zeros(5)  #zeros(5) -->  it forms 1-d arr in which all 5 ele will be 0
arr1

array([0., 0., 0., 0., 0.])

In [10]:
arr2=np.zeros((2,3))  #zeros((2,3)) -->  when we pass tuple it forms 2-d matrix in which all 5 ele will be 0  : 2 row and 3 col
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr3=np.zeros(5)    #ones(5) -->  similarily all ele will be 1
arr4=np.zeros((2,3))     
print(arr3)
print(end='\n')    #for new line
print(arr4)

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
arr5=np.eye(4)   #when we pass one val it creates 2-d matrix whose diagonal will be 1 and all other val will be 0
print(arr5)
print(end='\n')
arr6=np.eye(3,4)   #when we pass two val it also creates 2-d matrix whose diagonal will be 1 and all other val will be 0
print(arr6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [13]:
arr7=np.diag([1,2,3,4])    #when we input a list , the no. of inputs we pass, it forms sq. matrix of that input and the diagonals will be the ele others will be 0
print(arr7)

print(end='\n')

print(np.diag(arr7))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

[1 2 3 4]


In [14]:
rand_arr=np.random.randint(1,15,4)   #the val we pass means that we want 4 random int btw 1 to 15 : 1 is inclusive(means can be generated in random no.) but 15 is exclusive
rand_arr


array([ 2,  9,  6, 11])

In [15]:
rand_arr=np.random.rand(2,3)   #it will give us 2-d arr whose value will be in btw 0 & 1 similarly we can pass 1 digit : give us 1-d arr
rand_arr

array([[0.80888041, 0.87735565, 0.88757803],
       [0.06121056, 0.2071231 , 0.05364024]])

In [16]:
rand_arr=np.random.randn(4)   #it will give random no.s which are centred to 0, includes -ve & +ve no. both; gives val based on standard normal distribution
rand_arr

array([ 0.05503617, -1.4767903 ,  0.79692109, -1.21450106])

### Reshaping of Data

In [17]:
arr=np.random.randint(1,100,50)
arr=arr.reshape(10,5)   #similarly we can reshape in 3-d arr also


In [18]:
arr

array([[70, 13, 75, 17, 19],
       [67, 39, 61, 92, 52],
       [96, 83, 58, 14, 80],
       [95, 69, 69, 27, 13],
       [77,  4,  9, 12, 92],
       [33, 69, 30, 96, 56],
       [15, 37, 15, 92, 49],
       [83, 85, 67, 52, 66],
       [87, 19, 11, 83, 75],
       [48, 65, 89, 40, 58]])

In [19]:
arr.shape

(10, 5)

### -1 in reshape()

In [20]:
arr=np.arange(1,111)

In [21]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110])

In [22]:
arr.reshape(-1,5)    #-1 sets the value for the reshaped arr

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110]])

### Generate Same Random numbers --> seed function

In [23]:
np.random.seed(12)
arr=np.random.randint(1,101,15).reshape(3,5)
arr

array([[76, 28,  7,  3,  4],
       [68, 77, 49, 23, 50],
       [53,  6, 14, 90, 35]])

In [24]:
arr.size

15

### Indexing and slicing 1-d arr

In [25]:
arr=np.array([5,10,15,20,25])
arr

array([ 5, 10, 15, 20, 25])

In [26]:
# indexing
print(arr[0])
print(arr[4])
print(arr[-1])
print(arr[-4])

5
25
25
10


In [27]:
# slicing
print(arr[:])
print(arr[0:2])
print(arr[-3:])

# start stop step
print(arr[1:4])
print(arr[1:4:2])

[ 5 10 15 20 25]
[ 5 10]
[15 20 25]
[10 15 20]
[10 20]


In [28]:
# reverse arr
print(arr[::-1])

[25 20 15 10  5]


### Indexing and Slicing 2-d arr

In [29]:
matrix=np.array([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
#Indexing using single bracket notation
print(matrix[0][1])
print(matrix[2][1])

10
40


In [31]:
#Indexing using double bracket notation
print(matrix[0,1])
print(matrix[2,2])
print(matrix[1,2])

10
45
30


In [32]:
# Slicing using single bracket notation
print(matrix[:2,:2])    #[[5,10]
                      #[20,25]]


[[ 5 10]
 [20 25]]


In [33]:
print(matrix[1:,1:])    #[[25,30]
                        #[40,45]]

[[25 30]
 [40 45]]


In [34]:
np.random.seed(123)
matrix2=np.random.randint(1,101,25).reshape(5,5)
matrix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [35]:
# [[87,98,97]
#[33,47,97]
#[79,37,97]]


print(matrix2[1:4,1:4])

[[87 98 97]
 [33 47 97]
 [79 37 97]]


### View vs Copy

In [51]:
arr=np.array([5,10,15,20,25,30])

In [52]:
# broadcasting
# arr[:2]=0
# arr

In [53]:
# view -> its just a shadow of original array ; no memory allocated to the new arr
# sliced_arr=arr[2:5]
# sliced_arr

In [54]:
# sliced_arr[:]=0

In [55]:
# sliced_arr

In [56]:
# arr

In [57]:
sliced_arr=arr[2:5].copy()   #the new arr allocates memory and copy from the original arr
sliced_arr

array([15, 20, 25])

In [58]:
sliced_arr[:]=0

In [59]:
sliced_arr

array([0, 0, 0])

In [60]:
arr

array([ 5, 10, 15, 20, 25, 30])

### Conditional Selection

In [76]:
arr=np.arange(1,11)

In [77]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
mask=arr>5

In [79]:
arr[mask]

array([ 6,  7,  8,  9, 10])

In [80]:
# arr[arr%2==0]

In [ ]:
arr[arr%2==0] = 0    #broadcasting

In [83]:
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

### Operations on array with scaler


In [4]:
arr=np.array([1,2,3,4])

In [5]:
arr*2

array([2, 4, 6, 8])

In [6]:
arr+5

array([6, 7, 8, 9])

### Operations on two or more array

In [8]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr3=np.array([9,10,11,12])

In [4]:
arr1*arr2    #we can multiply same arr also arr1*arr1

array([ 5, 12, 21, 32])

In [5]:
arr1**arr2

array([    1,    64,  2187, 65536])

In [9]:
arr1/arr1*arr3

array([ 9., 10., 11., 12.])

In [14]:
# matrix
# shape should be same
np.random.seed(123)
matrix1=np.random.randint(1,12,9).reshape(3,-1)
matrix2=np.random.randint(5,15,9).reshape(3,-1)

In [16]:
matrix1

array([[ 3,  3,  7],
       [ 2,  4, 11],
       [10,  7,  2]])

In [17]:
matrix2

array([[ 5,  6, 14],
       [ 5,  5, 14],
       [ 8,  9,  5]])

In [19]:
matrix1*matrix2

array([[ 15,  18,  98],
       [ 10,  20, 154],
       [ 80,  63,  10]])

In [20]:
matrix1.dot(matrix2)

array([[ 86,  96, 119],
       [118, 131, 139],
       [101, 113, 248]])

### some more functions

In [22]:
arr=np.array([2,80,1,97,5])
print(np.min(arr))
print(np.max(arr))

1
97


In [24]:
print(np.argmin(arr))    #position of min number
print(np.argmax(arr))    #position of max number

2
3


In [25]:
np.sqrt(arr)

array([1.41421356, 8.94427191, 1.        , 9.8488578 , 2.23606798])

In [27]:
print(np.exp(arr))      #there is a euler number - 2.71828; the power of the euler number is the elements in the arr

print(np.sin(arr))  

print(np.cos(arr))  

print(np.linspace(1,15,50))      #we want in the range of 1 to 15 50 equally spaced no.


[7.38905610e+00 5.54062238e+34 2.71828183e+00 1.33833472e+42
 1.48413159e+02]
[ 0.90929743 -0.99388865  0.84147098  0.37960774 -0.95892427]
[-0.41614684 -0.11038724  0.54030231 -0.92514754  0.28366219]
[ 1.          1.28571429  1.57142857  1.85714286  2.14285714  2.42857143
  2.71428571  3.          3.28571429  3.57142857  3.85714286  4.14285714
  4.42857143  4.71428571  5.          5.28571429  5.57142857  5.85714286
  6.14285714  6.42857143  6.71428571  7.          7.28571429  7.57142857
  7.85714286  8.14285714  8.42857143  8.71428571  9.          9.28571429
  9.57142857  9.85714286 10.14285714 10.42857143 10.71428571 11.
 11.28571429 11.57142857 11.85714286 12.14285714 12.42857143 12.71428571
 13.         13.28571429 13.57142857 13.85714286 14.14285714 14.42857143
 14.71428571 15.        ]


In [28]:
print(np.linspace(5,20,4))

[ 5. 10. 15. 20.]


In [32]:
arr2 = np.array([1,2,3,0],dtype='bool')
arr2

array([ True,  True,  True, False])

In [34]:
for i in arr2:
    print(i)

True
True
True
False


### Numpy Axis

In [38]:
np.random.seed(123)
matrix=np.random.randint(1,11,9).reshape(3,3)
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [39]:
np.sum(matrix)

39

In [43]:
# rows= 1 and col=0    ; if we want to find the min and max of a rows or cols
print(np.min(matrix,axis=1))
print(np.max(matrix,axis=0))

[3 2 1]
[ 7  4 10]


In [44]:
np.sum(matrix,axis=1)

array([13, 16, 10])

In [46]:
# cumulative sum
np.cumsum(matrix,axis=0)

array([[ 3,  3,  7],
       [ 5,  7, 17],
       [12,  9, 18]])

In [47]:
np.prod(matrix,axis=1)

array([63, 80, 14])

### Numpy: shuffle and unique

In [57]:
np.random.seed(123)
arr=np.random.randint(1,15,15)

In [58]:
arr

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [59]:
np.random.shuffle(arr)

In [60]:
arr

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [61]:
np.unique(arr)

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [62]:
np.unique(arr).size     #count elements

10

In [63]:
# return_index -> jo number h uski first occurence ka position
# return_counts -> jo number h uski occurence count krega
np.unique(arr,return_index=True, return_counts=True)

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([ 8,  1,  6,  0,  7, 12,  2,  3,  4, 14], dtype=int64),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))

### Numpy: Horizontal and Vertical Stacking

In [71]:
np.random.seed(123)
matrix1=np.random.randint(1,20,9).reshape(3,3)
matrix2=np.random.randint(20,40,9).reshape(3,3)

In [72]:
print(matrix1)
print(matrix2)

[[14  3  3]
 [ 7 18 11]
 [ 2  1 18]]
[[35 29 20]
 [34 20 35]
 [39 34 24]]


In [73]:
# 2 matrix ko concatenate krna h horizontally in x-axis
np.hstack((matrix1,matrix2))

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [74]:
# 2 matrix ko concatenate krna h vertically in y-axis
np.vstack((matrix1,matrix2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [76]:
# 2 arr ko concatenate krna h horizontally in x-axis
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 1, 1, 1, 0])

In [75]:
# 2 arr ko concatenate krna h vertically in y-axis
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [1, 1, 1, 0]])